### PR TITLE
New example for modbus

### PR DESCRIPTION
**Pull request by theSloopJohnB**
As a companion to the forum post, I have added this example of a basic modbus master.

I also updated the package file to install the example next to the Temperature Controller example installed with DCAF Core

There is an accompanying bin3 file that I install to the exbin location so that it can be found in example finder.

### CODE REVIEW

**Comment by pollockm** [comment]
The build was hanging for the entire weekend.  Killed the build, starting again.

**Comment by pollockm** [comment]
Consistently hangs on package builds.  In other news, we now have a one-hour timeout set for any package  build, so we'll at least never hang the server again.

**Comment by dbendele** [comment]
Comments after review:

1. Great example!
2. Please add the simple instructions to the readme file so that the example stands more on its own.
3. Do you think it would be good to hide array scrollbars in Modbus Slave Example so users don't try more than 8 elements in slave arrays?
4. Where does one configure the module for master/slave operation?
5. Add a picture (in Module documentation) of simple topology used for example.
6. Great example!
7. Do you want to provide a single-sentence description of Kepserver or a link?

**Comment by theSloopJohnB** [comment]
Thanks! I've addressed your points of feedback by adding new content to the README and adding in a picture.

The Slave Example VI is actually from the NI Modbus Library. I agree it would be nice to remove the scroll bars and otherwise pare it down to simplify what the user can do with it, but I'd rather just pull in their version rather than copy it.

**Pull request merged**
